language: generic
sudo: required

branches:
  only:
   - staging
   - trying
   - master

services:
  - docker

env:
  - TARGET=ansiblecheck
  - TARGET=internal-minimal
  - TARGET=metapackages
  - TARGET=shellcheck
  - TARGET=shfmtcheck

install:
 - docker build -qt appliance-build:latest docker

script:
 - ./scripts/docker-run.sh make $TARGET
